let gpuTypeList = [
  { name: 'NVIDIA H100', value: 0 },
  { name: 'NVIDIA A100', value: 0 },
  { name: 'NVIDIA H200', value: 0 },
  { name: 'NVIDIA H800', value: 0 },
  { name: 'NVIDIA A200', value: 0 },
  { name: 'NVIDIA A800', value: 0 },
  { name: 'NVIDIA L40s', value: 0 },
  { name: 'NVIDIA L40', value: 0 },
  { name: 'NVIDIA A40', value: 0 },
  { name: 'NVIDIA GeForce RTX 4090', value: 0 },
  { name: 'NVIDIA GeForce RTX 4080 Ti', value: 0 },
  { name: 'NVIDIA GeForce RTX 4080', value: 0 },
  { name: 'NVIDIA GeForce RTX 4070 Ti', value: 0 },
  { name: 'NVIDIA GeForce RTX 4070', value: 0 },
  { name: 'NVIDIA A30', value: 0 },
  { name: 'NVIDIA GeForce RTX 4060 Ti', value: 0 },
  { name: 'NVIDIA A10', value: 0 },
  { name: 'NVIDIA A10G', value: 0 },
  { name: 'NVIDIA GeForce RTX 4060', value: 0 },
  { name: 'NVIDIA GeForce RTX 3090 Ti', value: 0 },
  { name: 'NVIDIA GeForce RTX 3090', value: 0 },
  { name: 'NVIDIA GeForce RTX 3080 Ti', value: 0 },
  { name: 'NVIDIA GeForce RTX 3080', value: 0 },
  { name: 'NVIDIA GeForce RTX 3070 Ti', value: 0 },
  { name: 'NVIDIA GeForce RTX 3070', value: 0 },
  { name: 'NVIDIA GeForce RTX 3060 Ti', value: 0 },
  { name: 'NVIDIA A6000', value: 0 },
  { name: 'NVIDIA A5000', value: 0 },
  { name: 'NVIDIA A4000', value: 0 },
  { name: 'NVIDIA GeForce RTX 3060', value: 0 },
  { name: 'NVIDIA GeForce RTX 3050', value: 0 },
  { name: 'NVIDIA GeForce RTX 2080 Ti', value: 0 },
  { name: 'NVIDIA GeForce RTX 2080 Super', value: 0 },
  { name: 'NVIDIA GeForce RTX 2080', value: 0 },
  { name: 'NVIDIA GeForce RTX 2070 Super', value: 0 },
  { name: 'NVIDIA GeForce RTX 2070', value: 0 },
  { name: 'NVIDIA GeForce RTX 2060 Super', value: 0 },
  { name: 'NVIDIA GeForce RTX 2060', value: 0 },
  { name: 'NVIDIA Tesla T4', value: 0 },
  { name: 'NVIDIA Tesla T10', value: 0 },
  { name: 'NVIDIA Tesla T4i', value: 0 },
  { name: 'NVIDIA A2000', value: 0 }
]

export default gpuTypeList