let gpuTypeList = [
  { name: 'NVIDIA H100' },
  { name: 'NVIDIA A100' },
  { name: 'NVIDIA H200' },
  { name: 'NVIDIA H800' },
  { name: 'NVIDIA A200' },
  { name: 'NVIDIA A800' },
  { name: 'NVIDIA L40s' },
  { name: 'NVIDIA L40' },
  { name: 'NVIDIA A40' },
  { name: 'NVIDIA GeForce RTX 4090' },
  { name: 'NVIDIA GeForce RTX 4080 Ti' },
  { name: 'NVIDIA GeForce RTX 4080' },
  { name: 'NVIDIA GeForce RTX 4070 Ti' },
  { name: 'NVIDIA GeForce RTX 4070' },
  { name: 'NVIDIA A30' },
  { name: 'NVIDIA GeForce RTX 4060 Ti' },
  { name: 'NVIDIA A10' },
  { name: 'NVIDIA A10G' },
  { name: 'NVIDIA GeForce RTX 4060' },
  { name: 'NVIDIA GeForce RTX 3090 Ti' },
  { name: 'NVIDIA GeForce RTX 3090' },
  { name: 'NVIDIA GeForce RTX 3080 Ti' },
  { name: 'NVIDIA GeForce RTX 3080' },
  { name: 'NVIDIA GeForce RTX 3070 Ti' },
  { name: 'NVIDIA GeForce RTX 3070' },
  { name: 'NVIDIA GeForce RTX 3060 Ti' },
  { name: 'NVIDIA A6000' },
  { name: 'NVIDIA A5000' },
  { name: 'NVIDIA A4000' },
  { name: 'NVIDIA GeForce RTX 3060' },
  { name: 'NVIDIA GeForce RTX 3050' },
  { name: 'NVIDIA GeForce RTX 2080 Ti' },
  { name: 'NVIDIA GeForce RTX 2080 Super' },
  { name: 'NVIDIA GeForce RTX 2080' },
  { name: 'NVIDIA GeForce RTX 2070 Super' },
  { name: 'NVIDIA GeForce RTX 2070' },
  { name: 'NVIDIA GeForce RTX 2060 Super' },
  { name: 'NVIDIA GeForce RTX 2060' },
  { name: 'NVIDIA Tesla T4' },
  { name: 'NVIDIA Tesla T10' },
  { name: 'NVIDIA Tesla T4i' }
]

export default gpuTypeList